[info]
# Nostr Private key used to manage relay users
private_key = "<nostr nsec>"
# Relay urls to publish and restore user manage list
relays = ["ws://127.0.0.1:8080"]

# Use a randomly generated sting as an api key for the http endpoints
# Optional: if present enable http management endpoint
# api_key = "apikey"

# Optional
# api_listen_host = "127.0.0.1"
# Optional
# api_listen_port = 3000

# Optional
# grpc_listen_host = "127.0.0.1"
# Optional
# grpc_listen_port = 50001

